name: Publish Website to CPanel
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: '8.2'
          extensions: mbstring, bcmath, zip, pdo, pdo_mysql
  
    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
  
    - name: Copy .env.example to .env
      run: cp .env.example .env

    - name: Generate APP_KEY
      run: |
        php artisan key:generate --force
        echo "APP_KEY=$(php artisan key:generate --show)" >> .env

    - name: Run migrations
      run: php artisan migrate --force
  
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
  
    - name: Cache npm dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
  
    - name: Install npm dependencies
      run: npm install
  
    - name: Compile assets
      run: npm run production
  
    - name: Optimize Laravel
      run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache


    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp.coderpirate.com
        username: admin@coderpirate.com
        password: Minhaz@1332
        protocol: ftps 
        port: 21 
        local-dir: './'
        server-dir: '/public_html/'



